# Extra env variables
# env = MY_GLOBAL_ENV,setting

# Force Wayland for GTK (GIMP, Firefox, etc.)
env = GDK_BACKEND,wayland,x11

# Force Wayland for Qt (OBS, VLC, etc.)
env = QT_QPA_PLATFORM,wayland;xcb

# Fix for Electron apps (Discord, VS Code) to use Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Ensure cursor theme is consistent
env = XCURSOR_SIZE,24
